# frozen_string_literal: true

source 'https://rubygems.org'
ruby '~> 3.2'

gem 'tk'

group :development, :test do
  gem 'rspec',     '~> 3.0'
  gem 'rubocop',   require: false
  gem 'simplecov', require: false
end
